### ISSUE TITLE
Luxo Jr

### ISSUE THREAD

**Issue by nycnewman** [3a1b2c3/Honest-history-of-visual-effects-and-animation#1]
This is the one film that I remember from the early days of animation

https://en.wikipedia.org/wiki/Luxo_Jr.

Saw it at an event in London in 1986.

**Comment by 3a1b2c3** [comment]
i will add it

**Comment by 3a1b2c3** [comment]
part of 1986 now

**Comment by nycnewman** [comment]
Thank you
